DI-27154 configuration scheme for events
Pepperi-Addons/user-defined-events pull request #54
Opened 2024-03-28 11:54 UTC by OdedAnswer

2024-03-28 11:58 UTC, roiaharon-pepperi requested changes

2024-03-28 11:58 UTC, roiaharon-pepperi commented on addon.config.json
> +  "AddonVersion": "0.7.6",
this needs to be changed to 0.8.0

2024-03-28 11:58 UTC, roiaharon-pepperi commented on shared/src/entities.ts
> +        LogicBlocks: {
please remove the LogicBlocks, this shouldn't be here

2024-03-28 12:07 UTC, OdedAnswer commented on addon.config.json
> +  "AddonVersion": "0.7.6",
right forgot

2024-03-28 12:08 UTC, OdedAnswer commented on shared/src/entities.ts
> +        LogicBlocks: {
but it is possible to have LogicBlocks, we said we allow them both and that they are mutually exclusive

2024-03-28 14:20 UTC, roiaharon-pepperi commented on addon.config.json
> +  "AddonVersion": "0.7.6",
no, you shouldn't publish new versions with old version number

2024-03-31 10:01 UTC, roiaharon-pepperi approved these changes

2024-03-31 10:01 UTC, merged